

services:
  database_blis: 
    image: mysql:8.0
    container_name: database_blis
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=blis
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=blis
      - MYSQL_DATABASE=mydatabase
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    network_mode: host

  app:
    build: .
    container_name: blis_container
    volumes:
      - .:/app
      - /app/node_modules  
    ports:
      - "3000:3000"  
    network_mode: host
    command: npm run dev  
    environment:
      - NODE_ENV=development

volumes:
  mysql_data:
